#!/bin/bash

nyhetssak() {
#### laster ned informasjon
curl -s https://www.nrk.no/toppsaker.rss -o /tmp/toppsaker

totalnews=$(xq -x /rss/channel/item/title /tmp/toppsaker | wc -l)


for ((nyhetsnr=1; $totalnews <= 100; nyhetsnr++ )); do
    #### Henter div informasjon fra rss XML
    overskrift=$(xq -x //item[$nyhetsnr]/title /tmp/toppsaker) #| awk "NR==$nyhetsnr")
    kategori=$(xq -x //item[$nyhetsnr]/category /tmp/toppsaker) #| awk "NR==$nyhetsnr")
    tekst=$(xq -x //item[$nyhetsnr]/description /tmp/toppsaker) #| awk "NR==$nyhetsnr")
    lenke=$(xq -x //item[$nyhetsnr]/link /tmp/toppsaker) #| awk "NR==$nyhetsnr")
    tidspunkt=$(xq -x //item[$nyhetsnr]/dc:date /tmp/toppsaker | tr -d ',') #| awk "NR==$nyhetsnr" | tr -d ',')
    bilde=$(xq -x //item[$nyhetsnr]/media:content/@url /tmp/toppsaker) #| awk "NR==$nyhetsnr")

###BREAKINGNEWS
breakingnews() {

curl -s https://www.nrk.no/nyheter/siste.rss -o /tmp/breakingnews

#get nyhetsnr
nyhetsnr1=$((RANDOM % 10))

#### Henter div informasjon fra rss XML
    overskrift=$(xq -x //item[$nyhetsnr1]/title /tmp/breakingnews) #| awk "NR==$nyhetsnr")
    kategori=$(xq -x //item[$nyhetsnr1]/category /tmp/breakingnews) #| awk "NR==$nyhetsnr")
    tekst=$(xq -x //item[$nyhetsnr1]/description /tmp/breakingnews) #| awk "NR==$nyhetsnr")
    lenke=$(xq -x //item[$nyhetsnr1]/link /tmp/breakingnews) #| awk "NR==$nyhetsnr")
    tidspunkt=$(xq -x //item[$nyhetsnr1]/dc:date /tmp/breakingnews | tr -d ',') #| awk "NR==$nyhetsnr" | tr -d ',')
    bilde=$(xq -x //item[$nyhetsnr1]/media:content/@url /tmp/breakingnews) #| awk "NR==$nyhetsnr")

# quitter om nyheter er tomme:
if [ -z "$tidspunkt" ]; then
    return
else
    #### printer hentet informasjon
    echo -e "\033[1;31mSISTE NYTT\033[0m"; date -d $tidspunkt
    echo -e "\033[4;37m\n$overskrift\n\033[0m" #| tr -d '"'
    echo -e "\033[0;37m$tekst\033[0m\n" #| tr -d '"'
    echo -e "Temaer:\n$kategori"
    #### Hvis man har kitty, så får man graphics
        if [ -n "$KITTY_WINDOW_ID" ]; then
            kitty +kitten icat --align left $bilde &> /dev/null
        fi
    echo -e "Kilde: '$lenke'\n\n" #| tr -d '"'
fi

    sleep 1

rm /tmp/breakingnews
}

if [ "$((nyhetsnr % 10))" -eq 0 ];then
        breakingnews
fi

# quitter om nyheter er tomme:
if [ -z "$tidspunkt" ]; then
    breakingnews;nyhetssak
fi


    #### printer hentet informasjon
    echo -e "\033[1;34mNRK nyheter\033[0m"; date -d $tidspunkt
    echo -e "\033[4;37m\n$overskrift\n\033[0m" #| tr -d '"'
    echo -e "\033[0;37m$tekst\033[0m\n" #| tr -d '"'
    echo -e "Temaer:\n$kategori"
    #### Hvis man har kitty, så får man graphics
        if [ -n "$KITTY_WINDOW_ID" ]; then
            kitty +kitten icat --align left $bilde &> /dev/null
        fi
    echo -e "Kilde: '$lenke'\n\n" #| tr -d '"'

    sleep 1
done


rm /tmp/toppsaker
}

while true; do
    nyhetssak
done
